### ISSUE TITLE
rom-recipes Asset path incorrect

### ISSUE THREAD

**Issue by esmith13** [opengateware/arcade-gberet#1]
### Version (or build number)

0.1.0

### Steps to reproduce

using available zip file to create *.rom files needed results in an error -1

### Expected Behavior

Rom files should be successfully created without error

### Actual Behavior

error -1 occurs due to folders pre-populated in zip file being:
Assets/green_beret/common

instead of the correct path as expected by the Powershell Script:
Assets/gberet/common

renaming 'green_beret' to 'gberet' works as expected.

**Comment by boogermann** [comment]
Thanks, issue was fixed
